### ISSUE TITLE
mapbox is token is expired! (front page)

### ISSUE THREAD

**Issue by pythagoraswitch** [wbg-bigdata/uav4dev#10]
![image](https://cloud.githubusercontent.com/assets/4925075/23523358/910ab40a-ff54-11e6-8063-dc5107a633c2.png)

**Comment by pythagoraswitch** [comment]
cc: @Uav-development, @berikiushi, @brunosan

**Comment by brunosan** [comment]
The token is changed in this repo, but that is a fork of the link posted.
To see the fixed token visit https://wbg-bigdata.github.io/uav4dev/

We need to either:

- Fix the token on @Uav-development (only her/him can do it). 
- Delete the  @Uav-developmen and only use this link for this: https://wbg-bigdata.github.io/uav4dev/

anyways, access to is a blocker.

**Comment by pythagoraswitch** [comment]
Thank you, @brunosan ! I contacted @Uav-development for finding a solution for this.

**Comment by pythagoraswitch** [comment]
the original is now fixed on https://uav-development.github.io/ via 4b29a22
