### ISSUE TITLE
Change the top image?

### ISSUE THREAD

**Issue by pythagoraswitch** [wbg-bigdata/uav4dev#8]
The current default looks like this:
![image](https://cloud.githubusercontent.com/assets/4925075/18683568/c300119e-7f3e-11e6-9394-c3e1b7180730.png)

This feels a bit underwhelming for the first thing we see on the website. Also this is layered over the satellite imageries, and it might be a bit confusing for the first timer to play around. It also highlights the image processing issue of remote sensing images (i.e. roads taken by UAV aren’t aligned perfectly with satellite). 
1.  Perhaps we can start from other (non-dynamic) image for visual aesthetics, and feature this dynamic image with more caption/explanations?
2.  If we can clear the privacy concerns, I’d prefer residential area to be the default location with the same zoom level (see below), where you can see a water well (!) and small roads covered by the trees which would have been difficult to spot by satellites. These are already answering the pretty important question the development practitioners have: what can UAV see (that satellite can't)?
![image](https://cloud.githubusercontent.com/assets/4925075/18683650/1e0dcb4e-7f3f-11e6-87e6-d010f992713c.png)

**Comment by mireille-raad** [comment]
code updated - is this image/location good enough? 

<img width="1120" alt="screen shot 2017-05-24 at 6 12 21 pm" src="https://cloud.githubusercontent.com/assets/521705/26427844/a4dd224e-40ac-11e7-8640-952aee3c45a0.png">

Pending:

1. what caption/explanations need to be added?

**Comment by mireille-raad** [comment]
Here are some other screenshots.
Do you want me to add any of them in the webpage to drive home the point you made earlier about difference between satellite and uav?

<img width="1688" alt="screen shot 2017-05-24 at 6 03 34 pm" src="https://cloud.githubusercontent.com/assets/521705/26428230/924b62c4-40ae-11e7-92e6-73e4ce90cf0f.png">


![screen-shot-2017-05-24-at-6 04 03-pm](https://cloud.githubusercontent.com/assets/521705/26428273/c330e346-40ae-11e7-9944-7efe4e7aa1c2.jpg)

**Comment by mireille-raad** [comment]
- [ ] Add more interactive features.
- [ ] Make it a bit more obvious that user can interact

**Comment by pythagoraswitch** [comment]
top image has been changed in the original here d0675b9. we will move the checklist to the original repo.
