### ISSUE TITLE
Table: "Commercial UAVs Specialized for Cargo Delivery" wrong info & suggestion

### ISSUE THREAD

**Issue by pythagoraswitch** [wbg-bigdata/uav4dev#9]
![image](https://cloud.githubusercontent.com/assets/4925075/18685914/06b697b0-7f48-11e6-8cd2-f9720f8ba335.png)

Vayu:
Cost USD $**25-30k**
Cargo Capable **2.2kg** over 60-70km

Source: http://www.vayu.us/ and Daniel Pepper (CEO, Vayu)

Also, it would be nifty to include the cargo delivery type in this table, such as parachute (one-way delivery) or landing&take-off model (two-way delivery)

**Comment by mireille-raad** [comment]
this google spreadsheet is public, I clicked on view spreadsheet then i did the edit and it was reflected on website.  (you might have to clear browser cache to see changes)

1. do we need to change the security of the spreadsheets? if yes, can you email me privately the list of collaborators?
2. I added the column "cargo delivery type" - can you update the google spreadsheet with the correct value? ( I tried to visit some of the sites, but for example vayu's webpage is a contact form only)
